version: '3'

services:
  mariadb:
    build: ./database
    ports:
      - 3306:3306
    env_file:
      - ./database/.env
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
  
  adminer:
    build: ./adminer
    env_file: ./adminer/.env
    ports:
      - 8081:8080
    volumes:
      - ./adminer/adminer.css:/var/www/html/adminer.css
    depends_on:
      - mariadb
